[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
cpu-time = "1.0"
serde = { version = "1.0", features = ["derive"] }
simplelog = "0.12"
log = "0.4"
toml = "0.8"

[lib]
name = "my_library"
path = "src/lib.rs"
